version: "3.3"

services:
  db:
    container_name: challenge-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge-db
      MYSQL_USER: challenge-user
      MYSQL_PASSWORD: challenge-pass
    volumes:
      - .images/mysql/testing-db.sql:/docker-entrypoint-initdb.d/testing-db.sql

  nginx:
    container_name: challenge-nginx
    build: .images/nginx
    command: nginx -g "daemon off;"
    volumes:
      - .images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    links:
      - php
    ports:
      - "7700:80"
    depends_on:
      - db

  php:
    container_name: challenge-php
    build: .images/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db